### ISSUE TITLE
Please call “windcave”, “worldpay”, etc. “processors” instead of “services”

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#10]

**Comment by udayangaac** [comment]
Processor is a specific name. If we wanted add Google service to the application, We need to put it under services directory. If we called it as "processors", it is misleading.

**Comment by 314159** [comment]
Obviously, Windcave, Worldpay, Google, GitHub  and even Thermeon have services, but we are talking about payment card processors.

That is why I want the name to be specific.

**Comment by udayangaac** [comment]
See this, Google has web services and under web services we can find the api  called "Geo coding api". If we want to use it. We can put it under "interfaces/services/googe/geo_coding_api.go".

<img width="450" alt="Screenshot 2022-01-26 at 09 33 13" src="https://user-images.githubusercontent.com/49243124/151102134-9e962394-fe25-4a37-8935-7c92c02e635b.png">

#### Please note that above one is an example.

Worldpay  is a payment service provider. It has web services call "tripos cloud api", "tripos lane api" and "express api". We can put them like below.

- "interfaces/services/worldpay/tripos_cloud_api.go".
- "interfaces/services/worldpay/tripos_lane_api.go".
- "interfaces/services/worldpay/express_api.go".

<img width="339" alt="Screenshot 2022-01-26 at 09 30 27" src="https://user-images.githubusercontent.com/49243124/151102275-0c85648c-cdb6-4ca5-9cc3-8d7835c1e858.png">

**Comment by 314159** [comment]
My point is that we have a very specific type of service we use: payment processors.  We will not be using any other type of service (we will not be using Google's geo_coding for example).

If we do need to create other types of services, we can name them as well.

Perhaps you would feel better by creating a `processors` directory under `services`?

**Comment by udayangaac** [comment]
Sure @314159. I agree with you suggestion. We can create new directory under `services` called `processors`. It is much better than i did.
