### ISSUE TITLE
Select "processors: not "APIs"

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#11]
The selector should choose the processor, not the particular processor’s API (e.g. PxHit. PxPost, Express, triPOS Lanes, triPOS cloud, or express).  Partly this is because that distinction should be handled by the processor, and also because sometimes more than one API is needed to be used to accomplish the logical transaction (for example WorldPay PIN pad authorizations involve both TriPOS cloud and Express).

**Comment by udayangaac** [comment]
Yes I already changed it.
<img width="1240" alt="Screenshot 2022-01-25 at 23 25 23" src="https://user-images.githubusercontent.com/49243124/151088411-4a728517-1b07-4b7d-b08e-c55b7890a68d.png">
