### ISSUE TITLE
Use new type for uuidKey

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#12]
Keys for context.Context (e.g. uuidKey) should not be a built-in type — you should create your own type and use variables of that type. See https://pkg.go.dev/context#WithValue and it’s example.

**Comment by udayangaac** [comment]
key in WithValue func is a type of interface. So we can use whatever type we want. Yeah it's better have user defined type. Can you explain little bit  ? :)

**Comment by 314159** [comment]
Sure.  Contexts are often passed from one program to another or from one package to another.
You have keys that point to values, and the keys must be unique.

Can you imagine some other program or library using a UUID?  If you both had a "string" with the value "uuid" then you would have a conflict: Whose "uuid" should be returned if you ask for the "uuid"?  Like if you passed your context to a `Writer` that needs to record a UUID as well?

But if you create a new type, perhaps a "github.com/thermeon/payments-service/blahblah/contextKey" with a value "uuid", that will guaranty that you have a unique key.

```
package blahblah
...
type contextKey string
...
const uuidKey = contextKey("uuid")
 ```

That would make it impossible to have a conflict.

**Comment by 314159** [comment]
Yes.  That makes the type of uuidKey be `github.com/udayangaac/payments-service/common.ContextKey`.
