### ISSUE TITLE
Please follow the standard golang naming conventions

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#3]
See
- [https://go.dev/doc/effective_go#names](https://go.dev/doc/effective_go#names),
- [https://betterprogramming.pub/naming-conventions-in-go-short-but-descriptive-1fa7c6d2f32a](https://betterprogramming.pub/naming-conventions-in-go-short-but-descriptive-1fa7c6d2f32a),
- [https://dave.cheney.net/practical-go/presentations/qcon-china.html](https://dave.cheney.net/practical-go/presentations/qcon-china.html)

**Comment by udayangaac** [comment]
Yes I am.
