### ISSUE TITLE
Don’t repeat a directory name in the source code file name

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#4]
For example, `hit/pxhit.go` might become `hit.go`, `hit/api.go` or perhaps `api/hit.go`.

**Comment by udayangaac** [comment]
Agree. I am following it.

<img width="357" alt="Screenshot 2022-01-26 at 09 04 50" src="https://user-images.githubusercontent.com/49243124/151104355-ef221247-4943-4a39-8a41-32e5f69d39f5.png">
