### ISSUE TITLE
Use go-swagger to generate the server code from the swagger.yaml file

### ISSUE THREAD

**Issue by 314159** [udayangaac/boilerplate-golang#5]
And commit before you start to add to this

**Comment by 314159** [comment]
Also, please keep generated code and non-generated code in separate directories.

**Comment by udayangaac** [comment]
I agree it. I am already following it. See attached image. all generated codes are under infrastructures/server, infrastructures/clients/tripos and infrastructures/clients/triposlane directories. I generated the client's codes from specs provided by payment services.
<img width="357" alt="Screenshot 2022-01-26 at 09 04 50" src="https://user-images.githubusercontent.com/49243124/151099794-8a55bb58-5063-4cb4-95b6-469b350a1f67.png">
